version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: biblioteca-mysql
    restart: always
    environment:
      MYSQL_DATABASE: biblioteca_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: biblioteca-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_NAME=biblioteca_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db:
          condition: service_healthy

volumes:
  db_data: